controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: '/'
    controller: App\Controller\MainController::index

calcul:
    path: '/calcul/{number}'
    controller: App\Controller\MainController::indexter

hello :
    path: 'hello/{prenom}'
    controller : App\Controller\FormController::hello
    defaults:
        prenom : "Bryan"

tuteurs :
    path: '/tuteurs'
    #controller : App\Controller\FormController::listes
    controller : App\Controller\TuteurController::index

search_tuteur :
    path: '/search'
    controller: App\Controller\FormController::search

verify_tuteur :
    path: '/verify_tuteur'
    controller: App\Controller\FormController::verify
    methods : ['POST']